name: Build and Deploy Crate Docs

on:
  push:
    branches: [main]
    tags:
      - v*.*.*

jobs:
  docs:
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=8cpu-linux-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build documentation
        run: cargo doc --workspace --no-deps
        env:
          # taken from https://github.com/paradigmxyz/reth/blob/main/.github/workflows/book.yml
          RUSTDOCFLAGS: --cfg docsrs --show-type-layout --generate-link-to-definition --enable-index-page -Zunstable-options

      # TODO: make a special tag for doc commit when pushing v*.*.* tags

      # Deploy to gh-pages branch using peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          publish_branch: gh-pages
